services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: file:./data/dev.db
      SECRET_KEY: ${SECRET_KEY:?defina SECRET_KEY no .env}
      PORT: 3000
    volumes:
      - forum-db:/app/data

volumes:
  forum-db:
